sudo: required

language: python
python: 2.7

services:
  - docker

before_install:
  - docker build -t bmcv/galaxy-paraviewweb .
  - docker run -d -p 8777:8777 bmcv/galaxy-paraviewweb

script:
  - docker ps
